id: alien-maven-repository-plugin
name: Maven Artifact Resolver Plugin
version: ${project.version}
description: >
  Plugin that contains resolver for maven artifact
configuration_class: alien4cloud.repository.maven.PluginFactoryConfiguration
component_descriptors:
  - bean_name: configurable-maven-artifact-resolver-factory
    name: Maven Configurable Resolver Factory
    description: >
      Factory to create a configurable resolver for Maven repository
  - bean_name: maven-artifact-resolver
    name: Maven Resolver
    description: >
      Resolver for Maven repository's artifact